version: "3.9"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    restart: always
    command: ./manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A app beat -l info
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app